/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d9dadb',
        'on-background': '#191c1d',
        'on-secondary-container': '#006e6e',
        background: '#f8f9fa',
        'on-tertiary-container': '#51ca63',
        outline: '#727781',
        'secondary-container': '#90efef',
        secondary: '#006a6a',
        'surface-container-high': '#e7e8e9',
        'primary-fixed': '#d3e3ff',
        tertiary: '#00380f',
        'surface-container': '#edeeef',
        'surface-container-highest': '#e1e3e4',
        'on-surface-variant': '#424750',
        primary: '#002f59',
        'outline-variant': '#c2c6d1',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#83fc8e',
        'primary-container': '#00467f',
        'surface-bright': '#f8f9fa',
        'tertiary-container': '#005119',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'on-error': '#ffffff',
        'on-surface': '#191c1d',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e3e4',
        error: '#ba1a1a',
        surface: '#f8f9fa',
        'primary-fixed-dim': '#a3c9ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        editorial: '0 32px 32px rgba(25,28,29,0.04)',
        ambient: '0 8px 32px rgba(25,28,29,0.06)',
      },
    },
  },
  plugins: [],
}

